# Generated by Django 2.2 on 2020-12-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0002_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_order',
            name='total_spending',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
